INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (1, 'Inquiry', 'General customer inquiries', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (2, 'Inquiry', 'General customer inquiries', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (3, 'Inquiry', 'General customer inquiries', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (4, 'Inquiry', 'General customer inquiries', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (5, 'Inquiry', 'General customer inquiries', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (6, 'Complaint', 'Customer complaints', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (7, 'Complaint', 'Customer complaints', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (8, 'Complaint', 'Customer complaints', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (9, 'Complaint', 'Customer complaints', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (10, 'Complaint', 'Customer complaints', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (11, 'Feedback', 'Customer feedback', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (12, 'Feedback', 'Customer feedback', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (13, 'Feedback', 'Customer feedback', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (14, 'Feedback', 'Customer feedback', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (15, 'Feedback', 'Customer feedback', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (16, 'Technical Support', 'Technical support', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (17, 'Technical Support', 'Technical support', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (18, 'Technical Support', 'Technical support', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (19, 'Technical Support', 'Technical support', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (20, 'Technical Support', 'Technical support', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (21, 'Refund Request', 'Requests for ticket refunds', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (22, 'Refund Request', 'Requests for ticket refunds', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (23, 'Refund Request', 'Requests for ticket refunds', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (24, 'Refund Request', 'Requests for ticket refunds', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (25, 'Refund Request', 'Requests for ticket refunds', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (26, 'Lost Baggage', 'Reports of lost or delayed baggage', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (27, 'Lost Baggage', 'Reports of lost or delayed baggage', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (28, 'Lost Baggage', 'Reports of lost or delayed baggage', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (29, 'Lost Baggage', 'Reports of lost or delayed baggage', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (30, 'Lost Baggage', 'Reports of lost or delayed baggage', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (31, 'Flight Delay', 'Complaints about flight delays', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (32, 'Flight Delay', 'Complaints about flight delays', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (33, 'Flight Delay', 'Complaints about flight delays', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (34, 'Flight Delay', 'Complaints about flight delays', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (35, 'Flight Delay', 'Complaints about flight delays', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (36, 'Service Request', 'Requests for specific services', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (37, 'Service Request', 'Requests for specific services', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (38, 'Service Request', 'Requests for specific services', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (39, 'Service Request', 'Requests for specific services', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (40, 'Service Request', 'Requests for specific services', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (41, 'Promotion Inquiry', 'Inquiries about promotions', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (42, 'Promotion Inquiry', 'Inquiries about promotions', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (43, 'Promotion Inquiry', 'Inquiries about promotions', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (44, 'Promotion Inquiry', 'Inquiries about promotions', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (45, 'Promotion Inquiry', 'Inquiries about promotions', 5, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (46, 'Special Assistance', 'Requests for special assistance', 1, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (47, 'Special Assistance', 'Requests for special assistance', 2, 'N');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (48, 'Special Assistance', 'Requests for special assistance', 3, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (49, 'Special Assistance', 'Requests for special assistance', 4, 'Y');
INSERT INTO dim_interaction_type (InteractionType_Key, InteractionType, Description, SeverityLevel, IsEscalable) VALUES (50, 'Special Assistance', 'Requests for special assistance', 5, 'Y');