INSERT INTO dim_booking_channel VALUES (1, 'DO-010', 'Online Website', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'TV-247', 'Online Website', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'EV-560', 'Online Website', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'DH-428', 'Online Website', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'IX-623', 'Online Website', 'GDS (Global Distribution System)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'OU-073', 'Online Website', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'FG-893', 'Online Website', 'Metasearch', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'LN-277', 'Online Website', 'Corporate', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'KQ-574', 'Online Website', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'ZY-504', 'Online Website', 'Other', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'VU-454', 'Mobile App', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'HY-465', 'Mobile App', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'IH-184', 'Mobile App', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'MM-781', 'Mobile App', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KY-481', 'Mobile App', 'GDS (Global Distribution System)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'NT-875', 'Mobile App', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'WA-454', 'Mobile App', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'YJ-055', 'Mobile App', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'JZ-913', 'Mobile App', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'FF-511', 'Mobile App', 'Other', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'HJ-547', 'Travel Agency', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'ZB-826', 'Travel Agency', 'Indirect', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'GC-212', 'Travel Agency', 'OTA (Online Travel Agency)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'NX-328', 'Travel Agency', 'Meta Search', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'SY-667', 'Travel Agency', 'GDS (Global Distribution System)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'ES-660', 'Travel Agency', 'TMC (Travel Management Company)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'EC-946', 'Travel Agency', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'SC-684', 'Travel Agency', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'EA-807', 'Travel Agency', 'Leisure', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'VO-359', 'Travel Agency', 'Other', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'JC-978', 'Call Center', 'Direct', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'LL-236', 'Call Center', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'VV-645', 'Call Center', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'NS-279', 'Call Center', 'Meta Search', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'TP-822', 'Call Center', 'GDS (Global Distribution System)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'AJ-332', 'Call Center', 'TMC (Travel Management Company)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'NW-622', 'Call Center', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'WY-991', 'Call Center', 'Corporate', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'XH-599', 'Call Center', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'SF-597', 'Call Center', 'Other', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'GE-921', 'Kiosk', 'Direct', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'NJ-061', 'Kiosk', 'Indirect', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'QJ-806', 'Kiosk', 'OTA (Online Travel Agency)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'ZT-424', 'Kiosk', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'OY-075', 'Kiosk', 'GDS (Global Distribution System)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'KH-137', 'Kiosk', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'YS-879', 'Kiosk', 'Metasearch', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'IS-302', 'Kiosk', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KJ-273', 'Kiosk', 'Leisure', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'DT-030', 'Kiosk', 'Other', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'PF-275', 'Social Media Platform', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'QS-590', 'Social Media Platform', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'NF-030', 'Social Media Platform', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'LC-557', 'Social Media Platform', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'QM-911', 'Social Media Platform', 'GDS (Global Distribution System)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'JY-023', 'Social Media Platform', 'TMC (Travel Management Company)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'BQ-901', 'Social Media Platform', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'PA-022', 'Social Media Platform', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'FR-239', 'Social Media Platform', 'Leisure', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'WA-087', 'Social Media Platform', 'Other', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'QY-889', 'Airline Office', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'ZE-613', 'Airline Office', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'TU-635', 'Airline Office', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'RI-979', 'Airline Office', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'XG-008', 'Airline Office', 'GDS (Global Distribution System)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'NB-146', 'Airline Office', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'QF-139', 'Airline Office', 'Metasearch', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'GZ-823', 'Airline Office', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KI-686', 'Airline Office', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'ET-391', 'Airline Office', 'Other', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'ZF-689', 'Hotel Booking Site', 'Direct', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'JV-177', 'Hotel Booking Site', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'DD-826', 'Hotel Booking Site', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'QQ-655', 'Hotel Booking Site', 'Meta Search', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'DT-176', 'Hotel Booking Site', 'GDS (Global Distribution System)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'CU-494', 'Hotel Booking Site', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'NR-330', 'Hotel Booking Site', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'SV-951', 'Hotel Booking Site', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'PN-302', 'Hotel Booking Site', 'Leisure', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'CF-212', 'Hotel Booking Site', 'Other', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'JD-397', 'Car Rental Site', 'Direct', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'MY-951', 'Car Rental Site', 'Indirect', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'CL-476', 'Car Rental Site', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'AF-356', 'Car Rental Site', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'PX-012', 'Car Rental Site', 'GDS (Global Distribution System)', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'RI-445', 'Car Rental Site', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'DZ-570', 'Car Rental Site', 'Metasearch', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'MF-851', 'Car Rental Site', 'Corporate', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KD-850', 'Car Rental Site', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'IK-708', 'Car Rental Site', 'Other', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'HJ-696', 'Cruise Booking Site', 'Direct', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'AZ-021', 'Cruise Booking Site', 'Indirect', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'SJ-776', 'Cruise Booking Site', 'OTA (Online Travel Agency)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KG-171', 'Cruise Booking Site', 'Meta Search', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'ZO-606', 'Cruise Booking Site', 'GDS (Global Distribution System)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'KN-179', 'Cruise Booking Site', 'TMC (Travel Management Company)', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'QH-902', 'Cruise Booking Site', 'Metasearch', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'EW-138', 'Cruise Booking Site', 'Corporate', 'offline');
INSERT INTO dim_booking_channel VALUES (1, 'LT-167', 'Cruise Booking Site', 'Leisure', 'online');
INSERT INTO dim_booking_channel VALUES (1, 'NT-593', 'Cruise Booking Site', 'Other', 'offline');
